/*!
 * CCSDS Attitude Parameter Message (APM) header.
 *
 * APM messages contain attitude-related parameters for spacecraft and can include
 * attitude sensor data, maneuvers, and covariance information. This module
 * provides the message header; the full message structure is added incrementally.
 *
 * Reference: CCSDS 504.0-B-2 (Attitude Data Messages), table 3-1
 */

use crate::time::Epoch;

/// CCSDS APM message header (504.0-B-2 table 3-1).
#[derive(Debug, Clone)]
pub struct APMHeader {
    /// Format version; 2.0 for messages conforming to 504.0-B-2.
    pub format_version: f64,
    /// Optional classification marking.
    pub classification: Option<String>,
    /// Message creation date (UTC).
    pub creation_date: Epoch,
    /// Creating agency or operator (SANA organizations registry abbreviation).
    pub originator: String,
    /// Optional message identifier, unique within the originator's context.
    pub message_id: Option<String>,
    /// Header comment lines.
    pub comments: Vec<String>,
}

impl APMHeader {
    /// Creates a header with format version 2.0 and the current UTC time as
    /// the creation date.
    ///
    /// # Arguments
    /// - `originator`: creating agency or operator identifier.
    ///
    /// # Returns
    /// APMHeader: A header with defaulted optional fields.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::apm::APMHeader;
    /// let header = APMHeader::new("BRAHE");
    /// assert_eq!(header.format_version, 2.0);
    /// ```
    pub fn new(originator: &str) -> Self {
        Self {
            format_version: 2.0,
            classification: None,
            creation_date: Epoch::now(),
            originator: originator.to_string(),
            message_id: None,
            comments: Vec::new(),
        }
    }

    /// Sets the classification marking.
    ///
    /// # Arguments
    /// - `classification`: classification marking string (e.g. `"UNCLASSIFIED"`).
    ///
    /// # Returns
    /// APMHeader: The header with the classification marking set.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::apm::APMHeader;
    /// let header = APMHeader::new("BRAHE").with_classification("UNCLASSIFIED");
    /// assert_eq!(header.classification.as_deref(), Some("UNCLASSIFIED"));
    /// ```
    pub fn with_classification(mut self, classification: &str) -> Self {
        self.classification = Some(classification.to_string());
        self
    }

    /// Sets the message identifier.
    ///
    /// # Arguments
    /// - `message_id`: message identifier, unique within the originator's context.
    ///
    /// # Returns
    /// APMHeader: The header with the message identifier set.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::apm::APMHeader;
    /// let header = APMHeader::new("BRAHE").with_message_id("MSG-001");
    /// assert_eq!(header.message_id.as_deref(), Some("MSG-001"));
    /// ```
    pub fn with_message_id(mut self, message_id: &str) -> Self {
        self.message_id = Some(message_id.to_string());
        self
    }

    /// Sets the header comment lines.
    ///
    /// # Arguments
    /// - `comments`: comment lines to associate with the header.
    ///
    /// # Returns
    /// APMHeader: The header with the comment lines set.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::apm::APMHeader;
    /// let header = APMHeader::new("BRAHE").with_comments(vec!["generated by brahe".to_string()]);
    /// assert_eq!(header.comments.len(), 1);
    /// ```
    pub fn with_comments(mut self, comments: Vec<String>) -> Self {
        self.comments = comments;
        self
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use serial_test::parallel;

    #[test]
    #[parallel]
    fn test_apm_header_new_defaults() {
        let header = APMHeader::new("BRAHE");
        assert_eq!(header.format_version, 2.0);
        assert_eq!(header.originator, "BRAHE");
        assert!(header.classification.is_none());
        assert!(header.message_id.is_none());
        assert!(header.comments.is_empty());
    }

    #[test]
    #[parallel]
    fn test_apm_header_builders() {
        let header = APMHeader::new("BRAHE")
            .with_classification("UNCLASSIFIED")
            .with_message_id("MSG-001")
            .with_comments(vec!["generated by brahe".to_string()]);
        assert_eq!(header.classification.as_deref(), Some("UNCLASSIFIED"));
        assert_eq!(header.message_id.as_deref(), Some("MSG-001"));
        assert_eq!(header.comments.len(), 1);
    }
}
