/*!
 * CCSDS Tracking Data Message (TDM) header.
 *
 * TDM messages contain tracking observations (ranges, Doppler, angles) from
 * ground stations or other platforms and can include covariance information.
 * This module provides the message header; the full message structure is added
 * incrementally.
 *
 * Reference: CCSDS 503.0-B-2 Cor.1 (Tracking Data Messages)
 */

use crate::time::Epoch;

/// CCSDS TDM message header (CCSDS 503.0-B-2 Cor.1).
#[derive(Debug, Clone)]
pub struct TDMHeader {
    /// Format version; 2.0 for messages conforming to 503.0-B-2.
    pub format_version: f64,
    /// Message creation date (UTC).
    pub creation_date: Epoch,
    /// Creating agency or operator (SANA organizations registry abbreviation).
    pub originator: String,
    /// Optional message identifier, unique within the originator's context.
    pub message_id: Option<String>,
    /// Header comment lines.
    pub comments: Vec<String>,
}

impl TDMHeader {
    /// Creates a header with format version 2.0 and the current UTC time as
    /// the creation date.
    ///
    /// # Arguments
    /// - `originator`: creating agency or operator identifier.
    ///
    /// # Returns
    /// TDMHeader: A header with defaulted optional fields.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::tdm::TDMHeader;
    /// let header = TDMHeader::new("BRAHE");
    /// assert_eq!(header.format_version, 2.0);
    /// ```
    pub fn new(originator: &str) -> Self {
        Self {
            format_version: 2.0,
            creation_date: Epoch::now(),
            originator: originator.to_string(),
            message_id: None,
            comments: Vec::new(),
        }
    }

    /// Sets the message identifier.
    ///
    /// # Arguments
    /// - `message_id`: message identifier, unique within the originator's context.
    ///
    /// # Returns
    /// TDMHeader: The header with the message identifier set.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::tdm::TDMHeader;
    /// let header = TDMHeader::new("BRAHE").with_message_id("MSG-001");
    /// assert_eq!(header.message_id.as_deref(), Some("MSG-001"));
    /// ```
    pub fn with_message_id(mut self, message_id: &str) -> Self {
        self.message_id = Some(message_id.to_string());
        self
    }

    /// Sets the header comment lines.
    ///
    /// # Arguments
    /// - `comments`: comment lines to associate with the header.
    ///
    /// # Returns
    /// TDMHeader: The header with the comment lines set.
    ///
    /// # Examples
    /// ```
    /// use brahe::ccsds::tdm::TDMHeader;
    /// let header = TDMHeader::new("BRAHE").with_comments(vec!["generated by brahe".to_string()]);
    /// assert_eq!(header.comments.len(), 1);
    /// ```
    pub fn with_comments(mut self, comments: Vec<String>) -> Self {
        self.comments = comments;
        self
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use serial_test::parallel;

    #[test]
    #[parallel]
    fn test_tdm_header_new_defaults() {
        let header = TDMHeader::new("BRAHE");
        assert_eq!(header.format_version, 2.0);
        assert_eq!(header.originator, "BRAHE");
        assert!(header.message_id.is_none());
        assert!(header.comments.is_empty());
    }

    #[test]
    #[parallel]
    fn test_tdm_header_builders() {
        let header = TDMHeader::new("BRAHE")
            .with_message_id("MSG-001")
            .with_comments(vec!["generated by brahe".to_string()]);
        assert_eq!(header.message_id.as_deref(), Some("MSG-001"));
        assert_eq!(header.comments.len(), 1);
    }
}
