language: python

notifications:
  email: false

python:
  - '3.6'
  - '3.7'

dist: xenial

before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements/requirements-dev.txt

script:
  - pytest --cov=brahe
  - travis-sphinx --outdir docs/build build --source docs/source

after_success:
  - coveralls
  - travis-sphinx --outdir docs/build deploy

deploy:
  provider: pypi
  user:
    secure: TrbxvXBZ93XMw8Mh/siMP5myoqGxEzyV5TYGTE2zwOyzMgnZ6xoHVj0Fcwtj+DvYFOs9Hfv4VrlyoX7bjprbRTGEiyZvz5NL9JbbJkjhbxzdQW0T+SnxNgdm/IlnpnIoagZUaS9X7Bt3SL0xqRXNwCTpsZMInPtx1D9njU7S+RNnBc9GpiDVjeWsVBR4PJ4+xYfLOd6RcerKW2jVqJ5PL6XTKJb9wMg7cCgd4cuiWao7X3otQ0BQRYsFgj4z/5DBQ73/l3MvpR5m6DvgbravJMQaFXYECh9KEAK06jg9hfIFjJFSLbcWZAHYrquOHqk1bsL2EImEfNVWOjXZSbFcO0wODby0ryB9EVdNPIX6+6C1CddNT5hZVsORcPWaYWoW6BuINBNtJXmVFoV4/Z1riRoOg+r/Vy3AdXGIzqh7Uy/iggPkgkQuJwJbaMYGr4Lj5uQfJ5VhbwI/QpNqnzUfy7aXBGP7a6nAtQ0g620NxAv8FgEueMKO37HoL7ZLqd77MAvtvcL76T6NvzCqkGvnfv6M9UYSA3Cjx2cMW5bl0RNflUZlkA8TonA/FvBycU3Xns3qUCI18BAaVMgHcYdOKhVo7ikH0SqlLWg1UukhTKigMUseBdi4LVc9GklGVphnAM/1te1R2MuTfmlJBm7wWX76RbwjcjsQt7jYE1He7T8=
  password:
    secure: ao8ty7uQfHsUOto4U6oTOgiUyG8QLDFVgTv9FxaUv6PBeN1zV4IBL3sJIjUxtQODF7to2nH5QFuuu9lLw6Dj0T5XhoWyM3K+lSstwI6EidUBXGYKls1eoNpN2o7DaSSkAmcvh0BiniBfwXhJTry/++X4jokB8w/t7PiS/9ioP86lT0kFKqCPYiklJuk014aFwBEoW66gv08FhGHPpr0ByhGGqgRLoW5tUow9I1V/cUmoS2ma/x++PSTIUdyRU0h2wN9tmzvw7jRr4Jj9Z2IF6SjMNUPrD2M2/jYdDZDV3YMALoyAjjstmzT8Ka+oSyxmzu0DN1n2TZ88WzKQRWWdtEYBn5UXGU26+MjWk7FccXh46wn/o526fxDNTgHawqbADiDo+opD7g8ib7YhhS31nxEkUCz9Tcc7Bg+JfZZmXlvmsoq9TjTVZKIMpThpSGNvcWUfpKRZtEYYiATtB8ecuI5cb451Jodnk/CmctVd8BSVAWdV7e3vrMzuPTFIG/QfLc6vMaild5mNidHBjEpAQ6bMyL8GemJr9xVYBbrzNpyoLAVnNMLB1vjzHurZ7ijy0hLmp2yHfVhr1UwQ+VJAmxbjrGmje2VzebYGflM0zolHKi/KW5Je93t5thf+xrfrj8lT1ZvB/2zXDGkW1t07Yg8Fu3j2wW2+0vWUe8SYy5Q=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
