[package]
name = "brahe"
version = "0.1.0"
authors = ["Duncan Eddy <duncan.eddy@gmail.com>"]
edition = "2021"
description = """
Brahe is a modern satellite dynamics library for research and engineering
applications. It is designed to be easy-to-learn, high-performance, and quick-to-deploy. 
The north-star of the development is enabling users to solve meaningful problems 
and answer questions quickly, easily, and correctly.
"""
homepage = "https://https://duncaneddy.github.io/brahe/"
documentation = "https://docs.rs/brahe/"
repository = "https://github.com/duncaneddy/brahe/"
keywords = ["space", "astrodynamics", "satellite"]
categories = ["science"]
readme = "README.md"
license = "MIT"

[lib]
name = "brahe"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
rsofa = "0.5.0"
nalgebra = "0.32.3"
kd-tree = "0.5.3"
once_cell = "1.19.0"
geojson = "0.24.1"
uluru = "3.0.0"
num-traits = "0.2.18"
regex = "1.10.3"
is_close = "0.1.3"
numpy = "0.20.0"
ureq = "2.9.6"
strum = "0.26"
strum_macros = "0.26"

[dependencies.pyo3]
version = "0.20.2"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["extension-module"]

[dev-dependencies]
approx = "0.5.1"
rstest = "0.18.2"
serial_test = "3.0.0"
httpmock = "0.7.0"
tempfile = "3.10.0"

[features]
ci = []
python = []