[package]
name = "brahe"
version = "0.1.0"
authors = ["Duncan Eddy <duncan.eddy@gmail.com>"]
edition = "2021"
description = """
Brahe is a modern satellite dynamics library for research and engineering
applications. It is designed to be easy-to-learn, high-performance, and quick-to-deploy. 
The north-star of the development is enabling users to solve meaningful problems 
and answer questions quickly, easily, and correctly.
"""
homepage = "https://https://duncaneddy.github.io/brahe/"
documentation = "https://docs.rs/brahe/"
repository = "https://github.com/duncaneddy/brahe/"
keywords = ["space", "astrodynamics", "satellite"]
categories = ["science"]
readme = "README.md"
license = "MIT"
exclude = ["/test_data", "/test", "/scripts", "/docs", "/brahe", ".github"]

[lib]
name = "brahe"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib", "lib"]

[dependencies]
rsofa = "0.5.0"
nalgebra = "0.33.0"
numpy = "0.22.0"
kd-tree = "0.6.0"
once_cell = "1.20.2"
geojson = "0.24.1"
uluru = "3.1.0"
num-traits = "0.2.19"
regex = "1.11.0"
is_close = "0.1.3"
ureq = "2.9.7"
strum = "0.26.3"
strum_macros = "0.26.4"

[dependencies.pyo3]
version = "0.22.4"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["extension-module", "gil-refs"]

[dev-dependencies]
approx = "0.5.1"
rstest = "0.23.0"
serial_test = "3.1.1"
httpmock = "0.7.0"
tempfile = "3.13.0"

[features]
ci = []
python = []

# Build Profiles
[profile.dev]
opt-level = 0
lto = "off"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"