site_name: Brahe
site_author: Duncan Eddy
site_description: Brahe - Practical Astrodynamics
site_url: https://github.com/duncaneddy/brahe
repo_url: https://github.com/duncaneddy/brahe
docs_dir: docs
use_directory_urls: false

extra_css:
    - stylesheets/extra.css

plugins:
    - search
    -   mkdocstrings:
            handlers:
                python:
                    inventories:
                        - https://docs.python.org/3/objects.inv
                        - https://numpy.org/doc/stable/objects.inv
                    paths: [brahe]
                    options:
                        show_source: false
                        docstring_style: google
                        docstring_section_style: table
                        merge_init_into_class: true
                        show_if_no_docstring: false
                        show_signature_annotations: true
                        separate_signature: true
                        show_root_heading: true
                        show_root_full_path: false
                        show_symbol_type_heading: true
                        show_symbol_type_toc: true
                        members_order: source
                        show_bases: true
                        show_inheritance_diagram: false
                        find_stubs_package: true
                        allow_inspection: true
    - section-index
    -   git-revision-date-localized:
            enable_creation_date: true
            fallback_to_build_date: true
            enable_git_follow: false
            type: iso_date
            strict: false
theme:
    name: material
    logo: assets/icon.png
    favicon: assets/favicon.png
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    language: en
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes
        - toc.follow

markdown_extensions:
    - admonition
    - footnotes
    - tables
    -   toc:
            permalink: true
            toc_depth: 3

nav:
    -   Brahe:
            - index.md
            - installation.md
            - contributing.md
            - About: about/index.md
            - Design Decisions: about/design_decisions.md
            - Python Deprecation: about/python_deprecation.md
            - License: about/license.md
    -   Learn:
            - learn/index.md
            - Time: learn/time.md
            - Constants: learn/constants.md
            - Coordinate Transformations: learn/coordinate_transformations.md
            - Frame Transformations: learn/frame_transformations.md
            - Orbital Properties: learn/orbital_properties.md
            - Attitude Representation: learn/attitude_representation.md
            - Orbit Propagation:
                - learn/orbit_propagation/index.md
                - Keplerian Propagation: learn/orbit_propagation/keplerian_propagation.md
                - SGP Propagation: learn/orbit_propagation/sgp_propagation.md
    -   Examples:
            - examples/index.md
            - Propagating an Orbit: examples/propagating_an_orbit.md
            - Computing Ground Contacts: examples/computing_ground_contacts.md
            - Computing Doppler Shift: examples/computing_doppler_shift_for_pass.md
    -   Python API Reference:
            - library_api/index.md
            - Constants:
                - library_api/constants/index.md
                - Units: library_api/constants/units.md
                - Mathematical: library_api/constants/math.md
                - Time: library_api/constants/time.md
                - Physical: library_api/constants/physical.md
            - EOP:
                - library_api/eop/index.md
                - FileEOPProvider: library_api/eop/file_provider.md
                - StaticEOPProvider: library_api/eop/static_provider.md
                - Functions: library_api/eop/functions.md
            - Time:
                - library_api/time/index.md
                - Epoch: library_api/time/epoch.md
                - Conversions: library_api/time/conversions.md
            - Coordinates:
                - library_api/coordinates/index.md
                - Cartesian: library_api/coordinates/cartesian.md
                - Geodetic & Geocentric: library_api/coordinates/geodetic.md
                - Topocentric: library_api/coordinates/topocentric.md
            - Frames: library_api/frames.md
            - Orbits:
                - library_api/orbits/index.md
                - Keplerian Elements: library_api/orbits/keplerian.md
                - Two-Line Elements: library_api/orbits/tle.md
                - KeplerianPropagator: library_api/orbits/keplerian_propagator.md
                - SGPPropagator: library_api/orbits/sgp_propagator.md
                - Enumerations: library_api/orbits/enums.md
            - Attitude:
                - library_api/attitude/index.md
                - Quaternion: library_api/attitude/quaternion.md
                - Rotation Matrix: library_api/attitude/rotation_matrix.md
                - Euler Angles: library_api/attitude/euler_angles.md
                - Euler Axis: library_api/attitude/euler_axis.md
            - Trajectories:
                - library_api/trajectories/index.md
                - DTrajectory: library_api/trajectories/dtrajectory.md
                - STrajectory6: library_api/trajectories/strajectory6.md
                - OrbitTrajectory: library_api/trajectories/orbit_trajectory.md
    -   Rust API Reference: https://docs.rs/brahe
    -   Blog: https://duncaneddy.com

extra:
    analytics:
        provider: google
        property: G-H1DDT6G6K6