site_name: Brahe
site_author: Duncan Eddy
site_description: Brahe - Practical Astrodynamics
site_url: https://github.com/duncaneddy/brahe
repo_url: https://github.com/duncaneddy/brahe
docs_dir: docs
use_directory_urls: false

extra_css:
    - stylesheets/extra.css

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://cdn.plot.ly/plotly-latest.min.js

plugins:
    - search
    -   mkdocstrings:
            handlers:
                python:
                    inventories:
                        - https://docs.python.org/3/objects.inv
                        - https://numpy.org/doc/stable/objects.inv
                    paths: [brahe]
                    options:
                        show_source: false
                        docstring_style: google
                        docstring_section_style: table
                        merge_init_into_class: true
                        show_if_no_docstring: false
                        show_signature_annotations: true
                        separate_signature: true
                        show_root_heading: true
                        show_root_full_path: false
                        show_symbol_type_heading: true
                        show_symbol_type_toc: true
                        members_order: source
                        show_bases: true
                        find_stubs_package: true
                        show_inheritance_diagram: false
                        allow_inspection: true
    - section-index
    -   git-revision-date-localized:
            enable_creation_date: true
            fallback_to_build_date: true
            enable_git_follow: false
            type: iso_date
            strict: false
theme:
    name: material
    logo: assets/icon.png
    favicon: assets/favicon.png
    language: en
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes
        - toc.follow

markdown_extensions:
    - admonition
    - footnotes
    - tables
    -   toc:
            permalink: true
            toc_depth: 3
    -   pymdownx.highlight:
            anchor_linenums: true
            line_spans: __span
            pygments_lang_class: true
    -   pymdownx.inlinehilite
    -   pymdownx.snippets
    -   pymdownx.superfences
    -   pymdownx.tabbed:
            alternate_style: true
    -   pymdownx.details
    -   pymdownx.arithmatex:
            generic: true

nav:
    -   Brahe:
            - index.md
            - installation.md
            - contributing.md
            - Design Philosophy & Decisions: design.md
            - License: license.md
    -   Learn:
            - learn/index.md
            - Constants: learn/constants.md
            - Earth Orientation Data:
                - learn/eop/index.md
                - learn/eop/managing_eop_data.md
                - learn/eop/what_is_eop_data.md
            - Time: 
                - learn/time/index.md
                - learn/time/time_systems.md
                - learn/time/time_conversions.md
                - learn/time/epoch.md
            - Coordinate Transformations:
                - learn/coordinates/index.md
                - learn/coordinates/cartesean_transformations.md
                - learn/coordinates/geocentric_transformations.md
                - learn/coordinates/topocentric_transformations.md
            - Reference Frame Transformations: learn/frame_transformations.md
            - Orbital Properties: learn/orbital_properties.md
            - Attitude Representation: 
                - learn/attitude_representations/index.md
                - learn/attitude_representations/quaternions.md
                - learn/attitude_representations/rotation_matrices.md
                - learn/attitude_representations/euler_angles.md
                - learn/attitude_representations/euler_axis.md
            - Trajectories:
                - learn/trajectories/index.md
                - learn/trajectories/dtrajectory.md
                - learn/trajectories/strajectory6.md
                - learn/trajectories/orbit_trajectory.md
            - Two-Line Elements (TLEs): learn/two_line_elements.md
            - Orbit Propagation:
                - learn/orbit_propagation/index.md
                - Keplerian Propagation: learn/orbit_propagation/keplerian_propagation.md
                - SGP Propagation: learn/orbit_propagation/sgp_propagation.md
            - Access Computation:
                - learn/access_computation/index.md
                - Locations: learn/access_computation/locations.md
                - Constraints: learn/access_computation/constraints.md
                - Properties: learn/access_computation/properties.md
                - Computation: learn/access_computation/computation.md
            - Datasets:
                - learn/datasets/index.md
                - CelesTrak: learn/datasets/celestrak.md
                - Groundstations: learn/datasets/groundstations.md
    -   Examples:
            - examples/index.md
            - Downloading TLE Data: examples/downloading_tle_data.md
            - Predicting Ground Contacts: examples/ground_contacts.md
            - Calculating Doppler Complensation: examples/doppler_complementation.md
            - Visualizing Orbital Trajectories: examples/visualizing_orbital_trajectories.md
            - Computing Imaging Opportunities: examples/imaging_opportunities.md
    -   Python API Reference:
            - library_api/index.md
            - Constants:
                - library_api/constants/index.md
                - Units: library_api/constants/units.md
                - Mathematical: library_api/constants/math.md
                - Time: library_api/constants/time.md
                - Physical: library_api/constants/physical.md
            - EOP:
                - library_api/eop/index.md
                - CachingEOPProvider: library_api/eop/caching_provider.md
                - FileEOPProvider: library_api/eop/file_provider.md
                - StaticEOPProvider: library_api/eop/static_provider.md
                - Functions: library_api/eop/functions.md
            - Time:
                - library_api/time/index.md
                - Epoch: library_api/time/epoch.md
                - Conversions: library_api/time/conversions.md
            - Coordinates:
                - library_api/coordinates/index.md
                - Cartesian: library_api/coordinates/cartesian.md
                - Geodetic & Geocentric: library_api/coordinates/geodetic.md
                - Topocentric: library_api/coordinates/topocentric.md
                - Enumerations: library_api/coordinates/enums.md
            - Frames: library_api/frames.md
            - Orbits:
                - library_api/orbits/index.md
                - Keplerian Elements: library_api/orbits/keplerian.md
                - Two-Line Elements: library_api/orbits/tle.md
                - KeplerianPropagator: library_api/orbits/keplerian_propagator.md
                - SGPPropagator: library_api/orbits/sgp_propagator.md
                - Enumerations: library_api/orbits/enums.md
            - Attitude:
                - library_api/attitude/index.md
                - Quaternion: library_api/attitude/quaternion.md
                - Rotation Matrix: library_api/attitude/rotation_matrix.md
                - Euler Angles: library_api/attitude/euler_angles.md
                - Euler Axis: library_api/attitude/euler_axis.md
            - Trajectories:
                - library_api/trajectories/index.md
                - DTrajectory: library_api/trajectories/dtrajectory.md
                - STrajectory6: library_api/trajectories/strajectory6.md
                - OrbitTrajectory: library_api/trajectories/orbit_trajectory.md
            - Datasets:
                - library_api/datasets/index.md
                - CelesTrak: library_api/datasets/celestrak.md
                - Groundstations: library_api/datasets/groundstations.md
            - Access:
                - library_api/access/index.md
                - Locations: library_api/access/locations.md
                - Constraints: library_api/access/constraints.md
                - Windows: library_api/access/windows.md
                - Enumerations: library_api/access/enums.md
    -   Rust API Reference: https://docs.rs/brahe
    -   Blog: https://duncaneddy.com

extra:
    analytics:
        provider: google
        property: G-H1DDT6G6K6
    version:
        provider: mike
        default: latest