site_name: Brahe
site_author: Duncan Eddy
site_description: Brahe - Practical Astrodynamics
site_url: https://github.com/duncaneddy/brahe
repo_url: https://github.com/duncaneddy/brahe
docs_dir: docs
use_directory_urls: false

extra_css:
    - stylesheets/extra.css

plugins:
    - search
    -   mkdocstrings:
            handlers:
                python:
                    options:
                        show_source: false
                        docstring_style: google
                        docstring_section_style: table
                        merge_init_into_class: true
                        show_if_no_docstring: false
                        show_signature_annotations: true
                        separate_signature: true
                        show_root_heading: true
                        show_root_full_path: false
                        show_symbol_type_heading: true
                        show_symbol_type_toc: true
    - section-index
    -   git-revision-date-localized:
            enable_creation_date: true
            fallback_to_build_date: true
            enable_git_follow: false
            type: iso_date
            strict: false
theme:
    name: material
    logo: assets/icon.png
    favicon: assets/favicon.png
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    language: en
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.follow

markdown_extensions:
    - admonition
    - footnotes
    - tables
    -   toc:
            permalink: true
            toc_depth: 3

nav:
    -   Brahe:
            - index.md
            - installation.md
            - contributing.md
    -   Learn:
            - learn/index.md
    -   Examples:
            - examples/index.md
    -   Python API Reference:
            - library_api/index.md
            - Constants: library_api/constants.md
            - EOP: library_api/eop.md
            - Time: library_api/time.md
            - Coordinates: library_api/coordinates.md
            - Frames: library_api/frames.md
            - Orbits: 
                - library_api/orbits/index.md
                - library_api/orbits.md
            - Attitude: library_api/attitude.md
            - Trajectories: library_api/trajectories.md
    -   Rust API Reference: https://docs.rs/brahe
    -   About:
            - about/index.md
            - about/design_decisions.md
            - about/license.md
    -   Blog: https://duncaneddy.com

extra:
    analytics:
        provider: google
        property: G-H1DDT6G6K6