site_name: Brahe
site_author: Duncan Eddy
site_description: Brahe - easy-to-learn, high-performance, and quick-to-deploy
site_url: https://github.com/duncaneddy/brahe
repo_url: https://github.com/duncaneddy/brahe
docs_dir: pages
use_directory_urls: false

extra_css:
    - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - section-index
    -   git-revision-date-localized:
            enable_creation_date: true
            fallback_to_build_date: true
            type: iso_date
theme:
    name: material
    logo: assets/icon.png
    favicon: assets/favicon.png
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    language: en
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: custom # Star-Trek Orange
            accent: black
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.follow

markdown_extensions:
    - admonition
    - footnotes
    - tables
    -   toc:
            permalink: true
            toc_depth: 3

nav:
    -   Brahe: index.md
    -   Getting Started (Tutorials & Guides):
            - getting_started/index.md
            - getting_started/installation.md
            - getting_started/first_script.md
            - getting_started/frame_conversion.md
            - getting_started/contact_prediction.md
            - getting_started/orbit_prediction.md
            - getting_started/tle_download.md
    -   Library API:
            - library_api/index.md
    -   Reference:
            - reference/index.md
            - reference/constants.md
    -   About:
            - about/index.md
            - about/roadmap.md
            - about/design_decisions.md
            - about/contributing.md
            - about/license.md
            - about/contact.md
    -   Blog: https://duncaneddy.com

extra:
    analytics:
        provider: google
        property: G-437544299