name: Unit Tests

on:
    push:
        branches:
            - main

jobs:
    test-rust:
        uses: ./.github/workflows/test_rust.yml
    test-python:
        uses: ./.github/workflows/test_python.yml
        needs: [ test-rust ]  # Depends on test-rust which includes pre-cache-python
    test-examples:
        uses: ./.github/workflows/test_examples.yml
        needs: [ test-rust, test-python ]
    update-docs:
        uses: ./.github/workflows/update_docs.yml
        needs: [ test-rust, test-python, test-examples ]