name: Commit Unit Tests

on:
    push:
        branches:
            - main

jobs:
    test-rust:
        uses: ./.github/workflows/test_rust.yml
    test-python:
        uses: ./.github/workflows/test_python.yml
        needs: [ test-rust ]